FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG VITE_API_URL
ARG VITE_SERVER_URL
ARG VITE_CLOUDFLARE_TURNSTILE_SITE_KEY
ARG VITE_PROXY_TARGET
ENV VITE_API_URL=$VITE_API_URL \
    VITE_SERVER_URL=$VITE_SERVER_URL \
    VITE_CLOUDFLARE_TURNSTILE_SITE_KEY=$VITE_CLOUDFLARE_TURNSTILE_SITE_KEY \
    VITE_PROXY_TARGET=$VITE_PROXY_TARGET

RUN npm run build

EXPOSE 5173

CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "5173"]
